project:
  type: website

website:
  title: "Personal notes"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: latest_overview.qmd
        text: Latest overview
      - text: Meetings
        menu: 
          - href: meeting notes/meeting01.qmd
            text: January
      - text: AI tools
        menu:
          - href: AItools/AI for Literature Review.qmd
            text: Literature

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

